spring:
  application:
    name: discovery-service
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
---
spring:
  profiles: peer1
server:
  port: 8761
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761